# ============================================================
#  MEDICAL-RDV — Configuration principale
# ============================================================

# --- MongoDB Atlas ---
mongo.uri=mongodb+srv://tiana:guillaume.com%21@medical.wcahfcn.mongodb.net/?retryWrites=true&w=majority
mongo.database=Medical

# --- JWT ---
jwt.secret=89bf663fde8f75c9ac9ad3bae84f6181f28a79f8ea558ff6a02bdb453819058d28289d9a18405a1477208adfa7e4c1a2f2078f9f1ad0c98c76c5ae60acfdee3b
jwt.expiration=86400000

# --- MailerSend ---
mailersend.api.key=mlsn.5782e3f67002c2b636de3dfffc6534f4832d27e73efa189839f693a3334147c5
mail.from=noreply@test-q3enl6k3rzm42vwr.mlsender.net
mail.from.name=Medical-Appointment

# --- Cloudinary ---
cloudinary.cloud_name=dffhgzc6a
cloudinary.api_key=771856135338288
cloudinary.api_secret=hNMj44RYg9RFgujLoPidZ0Adpg4

# --- App ---
app.cors.origin=http://localhost:5173

admin.email=admin@gmail.com
admin.password=admin123